source "https://rubygems.org"

# If you have any plugins, put them here!
group :jekyll_plugins do
	gem 'jekyll-tidy'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

